### ISSUE TITLE
DomainClassifier not installable on a fresh install

### ISSUE THREAD

**Issue by glyann** [adulau/DomainClassifier#2]
```
pip install DomainClassifier
```
On a clean install doesn't work.
(It can't retreive pybgpranking from DomainClassifier)

To get it to work, I needed a little trick : 
```
pip install DomainClassifier==0.7
pip install DomainClassifier
```

It seems to work properly but I don't think DomainClassifier 0.8 got everything.

**Comment by adulau** [comment]
Should be fixed in DomainClassifier v1.0
